# Generated by Django 4.2.4 on 2023-09-18 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='guns',
        ),
    ]
