# Generated by Django 4.2.4 on 2024-01-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_data_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='age',
        ),
    ]
